---
# Input datetime: House Setting Reset
#
# This is an automation control/setting to indicate when automations or
# manual overrides should reset.
#
# At this time, some things will "reset" for the next brand new day
#
name: "House Setting Reset"
icon: "mdi:restart"
has_time: true
has_date: false
