---
# Circadian Lighting slowly synchronizes your color changing lights with the
# regular naturally occuring color temperature of the sky throughout the day.
#
# This gives your environment a more natural feel, with cooler hues during
# the midday and warmer tints near twilight and dawn.
#
# https://github.com/claytonjn/hass-circadian_lighting
#
circadian_lighting:
  interval: 60
