---
# The Home Assistant Cloud allows you to quickly integrate your local
# Home Assistant with various cloud services like Amazon Alexa and Google Home.
#
# https://www.home-assistant.io/integrations/cloud/
#
cloud:

  # Customize the Google Assistant integration with the Naby Casa Cloud
  google_actions:

    # Entity specific configuration for Google Assistant.
    # These are loaded from a separate directory.
    entity_config: !include_dir_merge_named ../assistants/google

    # Filters for entities to include/exclude from Google Assistant.
    # These are loaded from a separate directory.
    filter:
      include_entities:
        - climate.bedroom_flynn
        - climate.bedroom_lilly
        - climate.bedroom_master
        - climate.living_room
        - fan.attic_ventilation
        - light.bedroom_lilly_bedside
        - light.bedroom_lilly_bedside
        - light.bedroom_master_ceiling
        - light.garden_wall
        - light.kitchen_ceiling
        - light.kitchen_cupboard
        - light.living_room_bartop
        - light.living_room_spotlight
        - light.living_room_television
        - light.living_room_window
        - light.office_desk
        - light.office_window
        - vacuum.living_room
