---
# The history component will track everything that is going on within
# Home Assistant and allows the user to browse through it.
#
# https://www.home-assistant.io/integrations/history/
#
history: ~
