---
# The HomeKit component allows you to forward entities from Home Assistant
# to Apple HomeKit, so they can be controlled from Appleâ€™s Home app and Siri.
#
# https://www.home-assistant.io/integrations/homekit
#
homekit:
  # Start the HomeKit Server automatically.
  # I have a Z-Wave network, but since Home Assistant restores entities,
  # we don't have to wait for it (like we did in the past).
  auto_start: true

  # The default: "Home Assistant Bridge", I like it to be just "Home Assistant"
  name: Home Assistant

  # Configuration for specific entities. Allows customization of names and types
  # These are imported from another folder, to decouple them from the packages.
  entity_config: !include_dir_named ../customizations/homekit

  # Filters for entities to be included / excluded from HomeKit.
  filter:
    include_entities: !include_dir_merge_list ../homekit
