---
# The input datetime integration allows the user to define
# date and time values that can be controlled via the
# frontend and can be used within automations and templates.
#
# https://www.home-assistant.io/integrations/input_datetime/
#
# I don't store my input datetime entities in my YAML configuration,
# instead I manage them via the Home Assistant frontend.
#
input_datetime: ~
