---
# The input_number integration allows the user to define values that can be
# controlled via the frontend and can be used within conditions of automation.
#
# The frontend can display a slider, or a numeric input box. Changes to the
# slider or numeric input box generate state events. These state events can be
# utilized as automation triggers as well.
#
# https://www.home-assistant.io/integrations/input_number/
#
# I don't store my input number entities in my YAML configuration,
# instead I manage them via the Home Assistant frontend.
#
input_number: ~
