---
# The input boolean integration allows the user to define boolean values
# that can be controlled via the frontend and can be used within conditions
# of automation. This can for example be used to disable or enable certain
# automations.
#
# https://www.home-assistant.io/integrations/input_boolean/
#
# I don't store my input boolean entities in my YAML configuration,
# instead I manage them via the Home Assistant frontend.
#
input_boolean: ~
