---
# The person integration allows connecting device tracker
# entities to one or more person entities.
#
# https://www.home-assistant.io/integrations/person/
#
# I don't store persons in my YAML configuration,
# instead I manage them via the Home Assistant frontend.
#
# Reasoning: Removes the need for me to juggle secrets.
#
person: ~
