---
# The person integration allows connecting device tracker
# entities to one or more person entities.
#
# https://www.home-assistant.io/components/person/
#
person: !include_dir_list ../entities/persons
