---
# Sensors are gathering information about states and conditions.
#
# This loads up my sensor configurations
#
# https://www.home-assistant.io/integrations/sensor/
#
sensor: !include_dir_list ../entities/sensors
