---
# This integration allows Spotify playback from Home Assistant
#
# https://www.home-assistant.io/integrations/spotify/
#
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
