---
# The sun component will use your current location to track if the sun is
# above or below the horizon.
#
# https://www.home-assistant.io/integrations/sun/
#
sun:
  # The (physical) elevation of your location, in meters above sea level.
  elevation: !secret zone_home_elevation
