---
#
# Telegram on your mobile or desktop device to send and receive messages
# or commands to/from your Home Assistant.
#
# Currently not really in use yet, but configured and I might use it in the
# near future.
#
# https://www.home-assistant.io/integrations/telegram_bot/
#
telegram_bot:
  - platform: webhooks
    api_key: !secret telegram_api_key
    parse_mode: markdown
    allowed_chat_ids:
      - !secret telegram_frenck
