---
# Text-to-Speech (TTS) enables Home Assistant to speak to you.
# This loads up my TTS service configurations
#
# https://www.home-assistant.io/components/tts/
#
tts: !include_dir_list ../entities/tts
