---
# The updater component will check daily for new releases.
# It will show a badge in the frontend if a new version is found.
# As Hass.io has its own schedule for release it doesnâ€™t make sense
# to use this component on Hass.io. Nevertheless, I'm still including it,
# since I like to know something is upcoming :)
#
# https://www.home-assistant.io/integrations/updater/
#
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
#
updater:
  # I chose to share some information with the Home Assistant developers.
  # It will help them to prioritize the development.
  # That why this option is enabled.
  reporting: true

  # I'm also reporting a list of components that I'm using.
  include_used_components: true
