---
# The zeroconf integration will scan the network for
# supported devices and services. Discovered integrations
# will show up in the discovered section on the integrations
# page in the config panel.
#
# https://www.home-assistant.io/integrations/zeroconf/
#
zeroconf: ~
