---
# Input boolean: Attic Variable Ventilation Manual Override
#
# This is a variable. I use variables internally in automations and are not
# meant to be used from the frontend.
#
# This variable indicates if the central ventilation system in the attic has
# been manually overriden by an user. If so, it will stop interfering with
# the ventilation system automatically.
#
name: "Attic Variable Ventilation Manual Override"
icon: "mdi:account-alert"
