---
# Input boolean: House Sleep Mode
#
# This mode is to indicate everybody is asleep. Some call this "night" mode,
# but I'm often awake at night ;) So, sleep mode feels more accurate.
#
# We general use the alarm system to determine this status, but its easier
# to use a input boolean in automations than dealing with all the states
# an alarm system provides.
#
# Also, if we change the way to detect this, got a new alarm system, or would
# want to control this manually for once, this makes that possible.
#
name: "House Sleep Mode"
icon: "mdi:sleep"
