---
# I store a lot of sensor data into InfluxDB, which allows me to query
# a longer history with ease. I use the Community Hass.io add-on for this,
# combined with the Community Hass.io Grafana add-on for the graphs.
#
# https://github.com/hassio-addons/addon-influxdb
# https://github.com/hassio-addons/addon-grafana
# https://www.home-assistant.io/components/influxdb/
#
influxdb:

  # This is the Hass.io add-on slug, allowing a direct connection to the addon.
  host: a0d7b954-influxdb
  port: 8086

  # The database name to store all the metrics in
  database: homeassistant

  # Authentication credentials
  username: !secret influxdb_username
  password: !secret influxdb_password

  # Max number of retries in case of a failure
  max_retries: 3

  # I like to specify (whitelist) each thing I'd like to put
  # into InfluxDB, to keep the database as clean as possible.
  include:
    entities:
      - climate.toon_van_eneco
