---
type: 'custom:compact-custom-header'
main_config: true
menu: show
notifications: clock
voice: hide
options: show
clock_format: 24
clock_am_pm: false
clock_date: false
exceptions:
  - conditions:
      user_agent: Mobile
    config:
      menu: overflow
      notifications: overflow
