---
repository:
  description: ":house: My Home Assistant config & docs (Hass.io based). Be sure to :star2: this repository for updates!"
  homepage: https://www.frenck.nl
  topics: homeassistant-config, home-assistant-config, home-assistant, homeassistant, hass, hassio, iot, internetofthings, internet-of-things, automation, homeautomation, home-automation
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  # Priority labels
  - name: "Priority: Critical"
    color: ee0701
    description: "This should be dealt with ASAP. Not fixing this issue would be a serious error."
  - name: "Priority: High"
    color: b60205
    description: "After critical issues are fixed, these should be dealt with before any further issues."
  - name: "Priority: Medium"
    color: 0e8a16
    description: "This issue may be useful, and needs some attention."
  - name: "Priority: Low"
    color: e4ea8a
    description: "Nice addition, maybe... someday..."

  # Type labels
  - name: "Type: Bug"
    color: ee0701
    description: "Inconsistencies or issues which will cause a problem for users or implementors."
  - name: "Type: Documentation"
    color: 0052cc
    description: "Solely about the documentation of the project."
  - name: "Type: Enhancement"
    color: 1d76db
    description: "Enhancement of the code, not introducing new features."
  - name: "Type: Feature"
    color: 0e8a16
    description: "New features or options."
  - name: "Type: Support"
    color: 5319e7
    description: "Marks an issue as an support ticket."
  - name: "Type: Discussion"
    color: d4c5f9
    description: "Marks an issue as an generic discussion ticket."
  - name: "Type: Maintaince"
    color: 2af79e
    description: "Generic maintaince tasks, e.g., package updates."

  # Additional markers
  - name: "Security"
    color: ee0701
    description: "Marks an security issues that needs to be resolved asap."
  - name: "Idea"
    color: fef2c0
    description: "Marks an idea, which might be excepted and implemented."
  - name: "Incomplete"
    color: fef2c0
    description: "Marks an PR or issue that is missing information."
  - name: "Pull request"
    color: fbca04
    description: "There is an PR opened for this issue."
  - name: "Accepted"
    color: c2e0c6
    description: "This issue or PR has been accepted."
  - name: "Declined"
    color: f9d0c4
    description: "This issue or PR has been declined."
  - name: "Potential duplicate"
    color: e6e6e6
    description: "This issue has been automatically marked as a potential duplicate."

  # Ongoing Status labels
  - name: "Status: Triage"
    color: fbca04
    description: "This issue needs to be triaged."
  - name: "Status: On hold"
    color: cccccc
    description: "Issue or PR that has been placed on hold for now."
  - name: "Status: In progress"
    color: fbca04
    description: "Issue is currently being resolved by a developer."
  - name: "Status: Stale"
    color: fef2c0
    description: "There has not been activity on this issue or PR for quite some time."
  - name: "Status: Awaiting response"
    color: fef2c0
    description: "Issue or PR awaits response from the creator."
  - name: "Status: Blocked"
    color: fef2c0
    description: "Progress on this issue is currently not possible."

  # Closing status labels
  - name: "Closed: Known limitation"
    color: e6e6e6
    description: "Issue is closed, it is a known limitation."
  - name: "Closed: Expected behavior"
    color: e6e6e6
    description: "Issues is closed, it is expected behavior."
  - name: "Closed: Duplicate"
    color: e6e6e6
    description: "Issue is closed, duplicate of an existing issue."
  - name: "Closed: Invalid"
    color: e6e6e6
    description: "Issue is closed, marked as not a valid issue (e.g., an user error)."
  - name: "Closed: Wrong repository"
    color: e6e6e6
    description: "Issue is closed, was created in the wrong repository."
  - name: "Closed: Won't Fix"
    color: e6e6e6
    description: "Issue is closed, it won't be fixed."
  - name: "Closed: Done"
    color: c2e0c6
    description: "Issue closed, work on this issue has been marked complete."

  # Others
  - name: "Beginner Friendly"
    color: 0e8a16
    description: "Good first issue for people wanting to contribute to the project."
  - name: "Help wanted"
    color: 0e8a16
    description: "We need some extra helping hands or expertise in order to resolve this."
  - name: "Hacktoberfest"
    description: "Issues/PRs are participating in the Hacktoberfest"
    color: fbca04

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        # required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: false
