---
alias: "Restroom Lights"
description: >-
  Automation to control the lights in our restroom.

  Handle the motion sensor and the house cleaning mode.

id: "973d9960-8290-42d4-a4d1-8fde7962a94a"
mode: queued
max_exceeded: silent
trace:
  stored_traces: 25

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automations_reloaded

  - platform: state
    entity_id:
      - binary_sensor.restroom_motion
      - input_boolean.house_mode_cleaning

  - platform: state
    id: "clear"
    entity_id: binary_sensor.restroom_motion
    from: "on"
    to: "off"
    for:
      minutes: 1

action:
  - choose:
      - alias: "Activate cleaning mode"
        conditions:
          - alias: "When house cleaning mode is active"
            condition: state
            entity_id: input_boolean.house_mode_cleaning
            state: "on"

        sequence:
          - alias: "Activate restroom cleaning scene"
            service: scene.turn_on
            target:
              entity_id: scene.restroom_cleaning
            data:
              transition: 2.5

      - alias: "Activate motion scene when motion is detected"
        conditions:
          - alias: "When motion detector is on"
            condition: state
            entity_id: binary_sensor.restroom_motion
            state: "on"

        sequence:
          - alias: "Activate restroom motion scene"
            service: scene.turn_on
            target:
              entity_id: scene.restroom_motion
            data:
              transition: 2.5

    default:
      - alias: "Turn off the restroom lights"
        service: light.turn_off
        target:
          area_id: restroom
        data:
          transition: 2
