---
image: docker:latest

stages:
  - preflight
  - homeassistant
  - esphome

# Generic preflight template
.preflight: &preflight
  stage: preflight
  tags:
    - preflight

# Generic Home Assistant template
.ha: &ha
  stage: homeassistant
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - python -m homeassistant --version
    - cp -R ./.stubs/* ./config
  script:
    - |
      python -m homeassistant \
        --config ./config/ \
        --script check_config \
        --info all
  tags:
    - test

# Generic ESPHome template
.esphome: &esphome
  stage: esphome
  variables:
    PYTHONPATH: "/usr/src/app:$PYTHONPATH"
  before_script:
    - esphome dummy.yaml version
    - cp -R ./.stubs/* ./config/esphome/
  script:
    - |
      for file in $(find \
        ./config/esphome \
        -type f \
        -name "*.yaml"\
        -not -name "secrets.yaml"
        ); do
        esphome $file config
      done
  tags:
    - test

# Preflight jobs
shellcheck:
  <<: *preflight
  image:
    name: koalaman/shellcheck-alpine:stable
    entrypoint: [""]
  before_script:
    - shellcheck --version
    - apk --no-cache add grep
    - |
      find . -type f -print0 | \
        xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
  script:
    - |
      for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir ".git" "${ADDON_TARGET}"); do
        if ! shellcheck $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

yamllint:
  <<: *preflight
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

jsonlint:
  <<: *preflight
  image: sahsu/docker-jsonlint
  before_script:
    - jsonlint --version || true
  script:
    - |
      for file in $(find . -type f -name "*.json"); do
        if ! jsonlint -q $file; then
          export FAILED=1
        else
          echo "$file OK"
        fi
      done
      if [ "${FAILED}" = "1" ]; then
        exit 1
      fi

markdownlint:
  <<: *preflight
  image:
    name: ruby:alpine
    entrypoint: [""]
  before_script:
    - gem install mdl
    - mdl --version
  script:
    - mdl --style all --warnings .

# Home Assistant test jobs
ha-latest:
  <<: *ha
  image:
    name: homeassistant/home-assistant:latest
    entrypoint: [""]

ha-rc:
  <<: *ha
  image:
    name: homeassistant/home-assistant:rc
    entrypoint: [""]
  allow_failure: true

ha-dev:
  <<: *ha
  image:
    name: homeassistant/home-assistant:dev
    entrypoint: [""]
  allow_failure: true

# ESPHome test jobs
esphome-latest:
  <<: *esphome
  image:
    name: esphome/esphome:latest
    entrypoint: [""]

esphome-beta:
  <<: *esphome
  image:
    name: esphome/esphome:beta
    entrypoint: [""]
  allow_failure: true

esphome-dev:
  <<: *esphome
  image:
    name: esphome/esphome:dev
    entrypoint: [""]
  allow_failure: true
