---
# Time
#
# The time component allows you to set up real time clock time sources
# for ESPHome.
#
# https://esphome.io/components/time.html
#
substitutions:
  time_timezone: "Europe/Amsterdam"

time:
  - <<: !include ../time/homeassistant.yaml
    timezone: "${time_timezone}"
  - <<: !include ../time/sntp.yaml
    timezone: "${time_timezone}"
