---
# The recorder component is storing details in a database which
# then are handled by the history component.
#
# https://www.home-assistant.io/components/recorder/
#
recorder:
  # The number of days of history to keep in the recorder database
  purge_keep_days: 3

  # How often (in days) the purge task runs
  purge_interval: 1
