---
# The version sensor platform is displaying the
# available version online.
#
# https://www.home-assistant.io/components/sensor.version/
#
platform: version
name: version_available
source: hassio
branch: stable
image: qemux86-64
