---
blueprint:
  name: Turn off lights when the alarm gets armed
  description: >
    A blueprint that turns off the selected lights when the alarm get armed.
  domain: automation
  input:
    alarm:
      name: Alarm Control Panel
      description: Alarm Control Panel to react on
      selector:
        entity:
          domain: alarm_control_panel
    armed_away:
      name: When the alarm is armed as "Away"
      default: true
      selector:
        boolean:
    armed_home:
      name: When the alarm is armed as "Home"
      default: true
      selector:
        boolean:
    armed_night:
      name: When the alarm is armed as "Night"
      default: true
      selector:
        boolean:
    armed_bypass:
      name: When the alarm is armed with a custom bypass
      default: true
      selector:
        boolean:
    lights:
      name: Lights
      description: Select one or multiple lights to turn off
      selector:
        target:
          entity:
            domain: light

trigger:
  - platform: state
    entity_id: !input alarm
    to:
      - armed_away
      - armed_bypass
      - armed_home
      - armed_night

variables:
  on_armed_away: !input armed_away
  on_armed_bypass: !input armed_bypass
  on_armed_home: !input armed_home
  on_armed_night: !input armed_night

condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - "{{ on_armed_away }}"
          - condition: state
            entity_id: !input alarm
            state: armed_away
      - condition: and
        conditions:
          - "{{ on_armed_bypass }}"
          - condition: state
            entity_id: !input alarm
            state: armed_bypass
      - condition: and
        conditions:
          - "{{ on_armed_home }}"
          - condition: state
            entity_id: !input alarm
            state: armed_home
      - condition: and
        conditions:
          - "{{ on_armed_night }}"
          - condition: state
            entity_id: !input alarm
            state: armed_night

action:
  - service: light.turn_off
    target: !input lights
    data:
      transition: 3
