---
alias: Climate
description: >-
  Controls the thermostat on Lilly's bedroom.

id: 48fa4f17-9a3b-4085-99ad-e16cbad5131f
mode: single

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at:
      - "07:00:00"
      - "17:30:00"

action:
  - choose:
      - conditions:
          - condition: time
            after: "17:30:00"
            before: "07:00:00"
        sequence:
          - service: climate.set_temperature
            data:
              entity_id: climate.bedroom_lilly
              hvac_mode: heat
              temperature: 19.0

    default:
      - service: climate.set_temperature
        data:
          entity_id: climate.bedroom_lilly
          hvac_mode: heat
          temperature: 17.0
