---
# The darksky platform uses the Dark Sky web service as a source for
# meteorological data for your location.
#
# https://www.home-assistant.io/integrations/weather.darksky/
#
platform: darksky
api_key: !secret darksky_api_key
mode: daily
