---
# Scene: Hall Sunrise
#
# A bit more bright and cool scene for during the sunrise. Wake up!
# There is already some light from the outside, so dim light won't do much.
#
id: "842949bc-17a6-4edb-9596-1c5bbb5550ba"
name: "Hall: Sunrise"
icon: mdi:weather-sunset-up
entities:
  light.hall_ceiling:
    brightness: 175
    color_mode: color_temp
    color_temp: 275
    state: "on"
