---
# Scene: Hall Sleep
#
# Used when the house is in sleep mode. This means someone is out of
# bed in the middle of the night, just enough light to see.
#
id: "73a7d53a-1a58-4117-a841-804e58f521ba"
name: "Hall: Sleep"
icon: mdi:sleep
entities:
  light.hall_ceiling:
    brightness: 25
    color_mode: color_temp
    color_temp: 454
    state: "on"
