---
# Dark blue theme by JuanMTech
#
# https://www.juanmtech.com/themes-in-home-assistant/3/
#
darkblue:
  # Main Interface Colors
  primary-color: "#2F7EFD"
  light-primary-color: "#6FA6FE"
  primary-background-color: "#1F1F28"
  secondary-background-color: var(--primary-background-color)
  divider-color: "#2F2F3D"

  # Text
  primary-text-color: "#FFFFFF"
  secondary-text-color: "#6FA6FE"
  text-primary-color: "#FFFFFF"
  disabled-text-color: "#4E4E66"

  # Sidebar Menu
  sidebar-icon-color: "#B6B6C1"
  sidebar-text-color: "#F1F1F1"
  sidebar-selected-background-color: var(--primary-background-color)
  sidebar-selected-icon-color: "#6FA6FE"
  sidebar-selected-text-color: var(--sidebar-selected-icon-color)

  # States and Badges
  state-icon-color: "#2F7EFD"
  state-icon-active-color: "#FBCD41"
  state-icon-unavailable-color: var(--disabled-text-color)

  # Sliders
  paper-slider-knob-color: "#2F7EFD"
  paper-slider-knob-start-color: var(--paper-slider-knob-color)
  paper-slider-pin-color: var(--paper-slider-knob-color)
  paper-slider-active-color: var(--paper-slider-knob-color)
  paper-slider-secondary-color: var(--light-primary-color)

  # Labels
  label-badge-background-color: "#23232E"
  label-badge-text-color: "#F1F1F1"
  label-badge-red: "#6FA6FE"

  # Cards
  paper-card-background-color: "#23232E"
  paper-listbox-background-color: var(--primary-background-color)

  # Toggles
  paper-toggle-button-checked-button-color: "#2F7EFD"
  paper-toggle-button-checked-bar-color: "#6FA6FE"
  paper-toggle-button-unchecked-button-color: var(--paper-toggle-button-checked-button-color)
  paper-toggle-button-unchecked-bar-color: "#3E4756"

  # Table row
  table-row-background-color: var(--primary-background-color)
  table-row-alternative-background-color: var(--secondary-background-color)
