purple:
  # Main colors
  primary-color: '#A599E970'
  accent-color: '#FAD000'
  dark-primary-color: '#7E46DF46'
  light-primary-color: '#B362FF88'
  # Text colors
  primary-text-color: '#A599E9'
  text-primary-color: 'var(--primary-text-color)'
  secondary-text-color: '#FAD000'
  disabled-text-color: '#777777'
  label-badge-border-color: 'green'
  # Sidebar
  sidebar-icon-color: '#A599E9'
  # Background colors
  primary-background-color: '#2D2B55'
  secondary-background-color: '#2D2B55'
  divider-color: 'rgba(0, 0, 0, .12)'
  table-row-background-color: '#7E46DF46'
  table-row-alternative-background-color: '#A599E942'
  # Nav Menu
  paper-listbox-color: '#777777'
  paper-listbox-background-color: '#1E1E3F'
  paper-grey-50: 'var(--primary-text-color)'
  paper-grey-200: '#222222'
  # Paper card
  paper-card-header-color: '#7E46DF46'
  paper-card-background-color: '#A599E942'
  paper-dialog-background-color: '#1E1E3F'
  paper-item-icon-color: 'var(--primary-text-color)'
  paper-item-icon-active-color: '#FAD000'
  paper-item-icon_-_color: 'green'
  paper-item-selected_-_background-color: '#A599E942'
  paper-tabs-selection-bar-color: 'green'
  # Labels
  label-badge-red: 'var(--primary-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  label-badge-background-color: '#222222'
  # Switches
  paper-toggle-button-checked-button-color: '#B362FF88'
  paper-toggle-button-checked-bar-color: '#B362FF88'
  paper-toggle-button-checked-ink-color: '#B362FF88'
  paper-toggle-button-unchecked-button-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'
  paper-toggle-button-unchecked-ink-color: 'var(--disabled-text-color)'
  # Sliders
  paper-slider-knob-color: '#B362FF88'
  paper-slider-knob-start-color: '#B362FF88'
  paper-slider-pin-color: '#B362FF88'
  paper-slider-active-color: '#B362FF88'
  paper-slider-container-color: 'linear-gradient(var(--primary-background-color), var(--secondary-background-color)) no-repeat'
  paper-slider-secondary-color: 'var(--secondary-background-color)'
  paper-slider-disabled-active-color: 'var(--disabled-text-color)'
  paper-slider-disabled-secondary-color: 'var(--disabled-text-color)'
  # Google colors
  google-red-500: '#b93829'
  google-green-500: '#B362FF88'
  # Changes to fix history/logbook menus
  lumo-primary-text-color: '#B362FF88'
  lumo-secondary-text-color: '#B362FF88'
  lumo-primary-color: '#B362FF88'
  # Calendar day numbers
  lumo-body-text-color: '#FAD000'
  # Calendar/Date-Picker Background
  lumo-base-color: '#222222'
  # Month/Year header
  lumo-header-text-color: 'var(--lumo-body-text-color)'
  # DayOfWeek Header
  lumo-tertiary-text-color: 'var(--lumo-body-text-color)'
  lumo-shade: '#222222'
  lumo-shade-90pct: 'rgba(34, 34, 34, .9)'
  lumo-shade-80pct: 'rgba(34, 34, 34, .8)'
  lumo-shade-70pct: 'rgba(34, 34, 34, .7)'
  lumo-shade-60pct: 'rgba(34, 34, 34, .6)'
  lumo-shade-50pct: 'rgba(34, 34, 34, .5)'
  lumo-shade-40pct: 'rgba(34, 34, 34, .4)'
  lumo-shade-30pct: 'rgba(34, 34, 34, .3)'
  lumo-shade-20pct: 'rgba(34, 34, 34, .2)'
  lumo-shade-10pct: 'rgba(34, 34, 34, .1)'
  lumo-shade-5pct: 'rgba(34, 34, 34, .05)'
  lumo-tint-5pct: '#222222'
  # fix for device configuration screen
  card-background-color: "var(--paper-card-background-color)"
  # Add Switch Config 
  switch-checked-color: "var(--paper-toggle-button-checked-button-color)"
  switch-unchecked-button-color: "var(--paper-toggle-button-unchecked-button-color)"
  switch-unchecked-color: "var(--paper-toggle-button-unchecked-bar-color)"
  switch-unchecked-track-color: "var(--paper-toggle-button-unchecked-bar-color)"