---
alias: Climate
description: >-
  Controls the thermostat in Flynn's bedroom.

  Besides normal temperature handling, this automation turns off the thermostat
  in Flynn's bedroom in case the window is open, and on again when its closed.

id: 995cb631-efde-4d01-a3b0-8bca47d546fe
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: binary_sensor.bedroom_flynn_window
  - platform: time
    at:
      - "07:00:00"
      - "17:30:00"

action:
  - choose:
      # Window is open
      - conditions:
          - condition: state
            entity_id: binary_sensor.bedroom_flynn_window
            state: "off"
        sequence:
          - service: climate.set_hvac_mode
            data:
              entity_id: climate.bedroom_flynn
              hvac_mode: "off"

      # High temperature
      - conditions:
          - condition: time
            after: "17:30:00"
            before: "07:00:00"
        sequence:
          - service: climate.set_temperature
            data:
              entity_id: climate.bedroom_flynn
              hvac_mode: heat
              temperature: 19.0

    # Default low
    default:
      - service: climate.set_temperature
        data:
          entity_id: climate.bedroom_flynn
          hvac_mode: heat
          temperature: 15.0
