---
# Light group: Master Bedroom Bedside
# We have 2 Xiaomi Bedside Lamps (Yeelight).
#
# This group allows me to handle them both at once
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: bedroom_master_bedside
entities:
  - light.bedroom_master_bedside_frenck
  - light.bedroom_master_bedside_daphne
