---
# Light group: Living Room
#
# This light controls all the other lights in my living room
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: living_room
entities:
  - light.living_room_bartop
  - light.living_room_dining_table
  - light.living_room_spotlight
  - light.living_room_television
  - light.living_room_window
