---
# Light group: Office
#
# This light controls all the other lights in my office
#
# https://www.home-assistant.io/integrations/light.group/
#
platform: group
name: office
entities:
  - light.office_desk_right
  - light.office_desk_left
  - light.office_window
