---
# Entity configuration for HomeKit.
#
# I use this to customize how the device shows up in HomeKit.
#
# https://www.home-assistant.io/components/homekit/#entity_config
#
light.livingroom_computer_corner:
  name: Computerhoek
