---
#
# Defines the Home Zone
#
# https://www.home-assistant.io/components/zone/
#
name: home
latitude: !secret zone_home_latitude
longitude: !secret zone_home_longitude
radius: 250
passive: false
icon: mdi:home
