---
# Entity configuration for Google Assistant.
#
# I use this to customize how the device shows up in Google Assistant.
#
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
#
light.master_bedroom_ceiling:
  name: Plafond
  aliases:
    - slaapkamer plafond
    - ceiling
    - master bedroom ceiling
    - master bedroom plafond
    - platfond
  room: Slaapkamer
