---
#
# Sunday morning, early morning, repack the recorder database.
# This keeps the disk usage low and nice by reclaiming space
# taken by the MySQL InnoDB database.
#
description: Repack recorder database
alias: system_recorder_repack
id: 752639e0-9527-45a6-84e8-f54537d40278
mode: single
trigger:
  - platform: time
    at: '05:55'
condition:
  - condition: time
    weekday:
      - sun
action:
  - service: recorder.purge
    data:
      repack: true
