---
description: Send notification on Home Assistant stop
alias: system_shutdown_notification
id: 761953d0-50cc-4f0b-81ff-3f305223ce38
mode: single
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.frenck_telegram
    data:
      message: Home Assistant is shutting down... Bye!
