---
# These are the entities from my kitchen that I want
# to store into InfluxDB.
#
# I like to specify (whitelist) each entity to store,
# since that keeps my InfluxDB clean and small.
#
[]
# - sensor.kitchen_fridge_current
# - sensor.kitchen_fridge_daily_energy
# - sensor.kitchen_fridge_power
# - sensor.kitchen_fridge_wifi_signal
