---
# Input number: Bathroom Setting Humidity Low
#
# This is an automation control/setting to indicate when
# the humidity in the bathroom is low.
#
name: "Bathroom Setting Humidity Low"
icon: "mdi:water-percent"
unit_of_measurement: "%"
min: 0
max: 100
step: 1
mode: slider
