---
# Circadian Lighting slowly synchronizes your color changing lights with the
# regular naturally occuring color temperature of the sky throughout the day.
#
# This switch allows me to enable or disable this feature on the lights
# on our garden wall.
#
# https://github.com/claytonjn/hass-circadian_lighting
#
platform: circadian_lighting
name: garden
lights_ct:
  - light.garden_wall
lights_xy:
  - light.garden_veranda_wall
lights_brightness:
  - light.garden_dinner_table
