---
alias: "Hall Curtains"
description: >-
  Automates the hall curtains, based on time and type of day.

  It also takes into account the modes of the house, like the ones
  that are triggered by the alarm or cleaning mode.

  TODO:
    - Move time triggers to automation settings (input helpers)

id: "bbc9e718-696f-43a5-af3a-3ea53701c6a7"
mode: queued
max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - input_boolean.house_mode_away
      - input_boolean.house_mode_cleaning
      - input_boolean.house_mode_guest
      - input_boolean.house_mode_sleep

  - platform: state
    id: "curtains"
    entity_id:
      - cover.hall_curtain

  - platform: time
    at:
      - "08:10:00"
      - "10:00:00"
      - "19:00:00"

  - platform: time
    id: "reset"
    at: input_datetime.house_setting_reset

action:
  - choose:
      - alias: "Reset manual override before the new day starts"
        conditions:
          - alias: "When triggerd by the reset time"
            condition: trigger
            id: time

        sequence:
          - &manual_override_off
            alias: "Reset manual override of the curtains"
            service: input_boolean.turn_off
            target:
              entity_id: input_boolean.hall_variable_curtains_manual_override

      - alias: "Activate cleaning mode"
        conditions:
          - alias: "When cleaning mode is on"
            condition: state
            entity_id: input_boolean.house_mode_cleaning
            state: "on"

        sequence:
          - *manual_override_off
          - &open_curtains
            alias: "Open curtains"
            service: cover.open_cover
            target:
              area_id: hall

      - alias: "Close curtains when sleep or away mode is active"
        conditions:
          - condition: or
            conditions:
              - alias: "When the house is in away mode"
                condition: state
                entity_id: input_boolean.house_mode_away
                state: "on"

              - alias: "When the house is in sleep mode"
                condition: state
                entity_id: input_boolean.house_mode_sleep
                state: "on"

        sequence:
          - *manual_override_off
          - &close_curtains
            alias: "Close curtains"
            service: cover.open_close
            target:
              area_id: hall

      - alias: "Ensure hall curtains are not manually overriden"
        conditions:
          - alias: "When manually overriden"
            condition: state
            entity_id: input_boolean.hall_variable_curtains_manual_override
            state: "on"

        # Do nothing, beyond this point, because of the manual override
        sequence: []

      - alias: "Manual hall curtains override detected"
        conditions:
          - alias: "Curtains have changed"
            condition: trigger
            id: "curtains"

          - alias: "It was changed by a user"
            condition: template
            value_template: "{{ trigger.to_state.context.user_id != None }}"

        sequence:
          - alias: "Set hall curtains as manually overriden"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.hall_variable_curtains_manual_override

      - alias: "Open curtains on weekdays"
        conditions:
          - alias: "When it is a weekday and curtains should be open"
            condition: time
            after: "08:10:00"
            before: "19:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri

          - alias: "When it is not a holiday"
            condition: state
            entity_id: binary_sensor.holiday
            state: "off"

        sequence:
          - *open_curtains

      - alias: "Open curtains on Saturday"
        conditions:
          - alias: "When it is a Saturday and curtains should be open"
            condition: time
            after: "10:00:00"
            before: "19:00:00"
            weekday:
              - sat

        sequence:
          - *open_curtains

      - alias: "Open curtains a holiday"
        conditions:
          - alias: "When it is a Holiday and curtains should be open"
            condition: time
            after: "10:00:00"
            before: "19:00:00"

          - alias: "When it is a holiday"
            condition: state
            entity_id: binary_sensor.holiday
            state: "on"

        sequence:
          - *open_curtains

    default:
      - *close_curtains
