---
# OTA (Over The Air) component
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/ota.html
#
substitutions:
  ota_password: !secret esphome_ota_password

ota:
  id: component_ota
  password: "${ota_password}"
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5
