---
# Pulse Meter Sensor - Water
#
# The pulse meter sensor allows you to count the number and frequency of pulses
# on any pin.
#
# This one is attached to my Water meter, and sends a pulse for each L of water
# used.
#
# https://esphome.io/components/sensor/pulse_meter.html
#
platform: pulse_meter
id: sensor_pulse_meter
name: "${name} Current Usage"
icon: "mdi:water-pump"
unit_of_measurement: "L/min"
timeout: 2min
accuracy_decimals: 1
total:
  id: sensor_pulse_meter_total
  name: "${name} Total Consumption"
  icon: "mdi:cube-outline"
  unit_of_measurement: "M3"
  accuracy_decimals: 3
  filters:
    - multiply: 0.001
