---
#
# SHTCx Temperature+Humidity Sensor
#
# The shtcx sensor platform Temperature+Humidity sensor allows you to use your
# Sensiron SHTC1 and the newer SHTC3 sensors with ESPHome.
#
# https://esphome.io/components/sensor/shtcx.html
#
platform: shtcx
temperature:
  id: sensor_temperature
  name: "${name} Temperature"
humidity:
  id: sensor_humidity
  name: "${name} Humidity"
update_interval: 600s
