---
# Turns down bedroom heating on working days.
# We probably are up early so save some energy.
#
# On working days, we turn down the heating at 7AM,
# on other days, we might stay in bed a little longer, so 10AM in that case.
#
description: Turn down the heating in the master bedroom
alias: master_bedroom_climate_low
id: 13c25f18-9328-4065-8ec6-215eb5462e33
mode: queued
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: time
    at:
      - "07:00:00"
      - "10:00:00"
condition:
  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday
            state: "on"
          - condition: time
            after: "07:00:00"
            before: "21:00:00"
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.workday
            state: "off"
          - condition: time
            after: "09:00:00"
            before: "21:00:00"
action:
  - service: climate.set_temperature
    data:
      entity_id:
        - climate.master_bedroom
      temperature: 15
