---
description: Turns the doorbell chime of when kids are sleeping
alias: porch_doorbell_chime_off
id: e7313dd1-3776-4740-9888-d7f15cf33158
trigger:
  - platform: template
    value_template: >-
      {{
        states('input_datetime.house_silent_hours_start')
        ==
        states('sensor.time')+":00"
      }}
action:
  - service: switch.turn_off
    data:
      entity_id:
        - switch.porch_doorbell_chime
