---
id: outside
title: Buiten
icon: mdi:nature-people
cards:
  - !include ../cards/compact_custom_header.yaml
  - type: custom:weather-card
    entity: weather.dark_sky
    icons: "/local/lovelace/icons/"
