---
# Device: Sonoff Basic
#
# This is my ESPHome device template for the Sonoff Basic
#
# It is close to the original functionality. No clouds :)
#
# https://www.itead.cc/sonoff-wifi-wireless-switch.html
#
packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp01s.yaml

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    id: device_button
    name: "${name} Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: device_relay

switch:
  # Switch to toggle the relay
  - platform: gpio
    id: device_relay
    name: "${name}"
    pin: GPIO12
    on_turn_on:
      - light.turn_on: device_led
    on_turn_off:
      - light.turn_off: device_led

output:
  # Output to control the Green LED
  - platform: esp8266_pwm
    id: device_output_led
    pin:
      number: GPIO13
      inverted: true

light:
  # Take the output and defines it as a light
  - platform: monochromatic
    id: device_led
    output: device_output_led
