---
# This template create a fan out of my Sonoff Dual with ESPHome.
#
# See esp03.yaml for the matching ESPHome configuration
#
# https://www.home-assistant.io/integrations/fan.template/
#
platform: template
fans:
  attic_ventilation:
    unique_id: 40b6baed-b37a-479c-a5eb-a1dd6817674d
    value_template: >-
      {% if is_state('switch.attic_ventilation_speed_off', 'off') %}
        on
      {% else %}
        off
      {% endif %}
    turn_on:
      - service: switch.turn_on
        data:
          entity_id: >-
            {% if speed == 'high' %}
              switch.attic_ventilation_speed_high
            {% else %}
              switch.attic_ventilation_speed_low
            {% endif %}
    turn_off:
      - service: switch.turn_on
        entity_id: switch.attic_ventilation_speed_off
    speed_template: >-
      {% if is_state('switch.attic_ventilation_speed_low', 'on') %}
        low
      {% elif is_state('switch.attic_ventilation_speed_high', 'on') %}
        high
      {% else %}
        off
      {% endif %}
    set_speed:
      - service: switch.turn_on
        data:
          entity_id: >-
            {% if speed == 'low' %}
              switch.attic_ventilation_speed_low
            {% elif speed == 'high' %}
              switch.attic_ventilation_speed_high
            {% else %}
              fan.attic_ventilation
            {% endif %}
    speeds:
      - "off"
      - "low"
      - "high"
