---
# Device: Sonoff Pow R2
#
# This is my ESPHome device template for the Sonof Pow R2.
#
# It is close to the original functionality, with the power sensor,
# the button, the LED even :)
#
# https://www.itead.cc/sonoff-pow-r2.html
#
packages:
  <<: !include_dir_named ../common
  board: !include ../boards/esp01s.yaml

# Enable UART for the power sensor
uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - <<: !include ../sensors/cse7766.yaml

switch:
  # This is the actual exposed power switch
  - platform: gpio
    name: "${name} Switch"
    id: device_relay
    pin: GPIO12

binary_sensor:
  # Binary sensor for the button press
  - platform: gpio
    id: device_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: device_relay

# Uses the blue LED as status indicator
status_led:
  pin:
    number: GPIO13
    inverted: true
