---
# Entity configuration for Google Assistant.
#
# I use this to customize how the device shows up in Google Assistant.
#
# https://www.home-assistant.io/integrations/google_assistant/#entity_config
#
climate.master_bedroom:
  name: Thermostaat
  aliases:
    - slaapkamer thermostaat
    - bedroom
    - bedroom thermostat
    - slaapkamer
    - temperatuur
    - themostaat
    - thermostaat
    - thermostat
  room: Slaapkamer
