---
alias: Automatic Lighting On
description: >-
  Reset / turn on garden automatic lighting when alarm is armed,
  or early in the morning

  It gets turned off when a manual override is detected, but will reset itself
  every night, or when the alarm gets armed.

id: 749a9def-8eb6-461a-9c20-9552e1a2693a

use_blueprint:
  path: automatic_control_on.yaml
  input:
    toggle: input_boolean.garden_automatic_lighting
