---
alias: Living Room Vacuum Dock
description: >-
  If the alarm gets disarmed, it means we are getting home. In those cases
  the running vacuum cleaner should run back for its dock.

id: 36eea376-104b-4fc9-8168-b25e389afcab
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.home_alarm
    to: "disarmed"

condition:
  - condition: state
    entity_id: vacuum.living_room
    state: "cleaning"

action:
  - service: vacuum.return_to_base
    target:
      entity_id: vacuum.living_room
