---
alias: "House Away Mode Detection"
description: >-
  Automation to control the away mode of the house automatically.

  This is mostly based on our alarm system at this point.

id: "3115d7be-d6de-4f1e-b852-213d1f2ddb01"
mode: queued

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm

condition:
  - alias: "Ensure the alarm system is available and has a known state"
    condition: not
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house_alarm
        state:
          - "unavailable"
          - "unknown"

action:
  - alias: "Decide if house should be in away mode or not"
    choose:
      - alias: "Turn on away mode"
        conditions:
          - alias: "When the alarm is armed away"
            condition: state
            entity_id: alarm_control_panel.house_alarm
            state: "armed_away"

        sequence:
          - alias: "Turn on house away mode"
            service: input_boolean.turn_on
            target:
              entity_id: input_boolean.house_mode_away

    default:
      - alias: "Turn off away mode"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.house_mode_away
