---
# Garage Washing Machine
#
# The washing machine in my garage is hooked up to an Sonoff POW R2.
#
# Right now, it just sends out power data to Home Assistant. I do have a
# small binary sensor, that can tell if the machine is "on"/standby.
#
# In the future I want to get power profiles and actually tell what the
# state of the machine is.
#
substitutions:
  slug: garage_washing_machine
  name: Garage Washing Machine
  description: The washing machine, mainly for power monitoring
  api_password: !secret esphome_garage_washing_machine_api_password
  ota_password: !secret esphome_garage_washing_machine_ota_password

packages:
  device: !include devices/sonoff_pow_r2.yaml

binary_sensor:
  # This binary sensor tells if the Washing Machine is powered on itself (display)
  - platform: template
    id: powered_on
    name: "${name} On"
    filters:
      - delayed_off: 10s
    lambda: |-
      return id(sensor_cse7766_power).state > 2;
