---
# Garage Dryer
#
# The dryer in my garage is hooked up to an Sonoff POW R2.
#
# It just sends out power data to Home Assistant. It is also able to tell
# if it is turned on/standby and exposes an additional sensor to indicate it
# it running.
#
substitutions:
  slug: garage_dryer
  name: Garage Dryer
  description: Monitors or dryer. It can also tell if it is running or not.
  api_password: !secret esphome_garage_dryer_api_password
  ota_password: !secret esphome_garage_dryer_ota_password

packages:
  device: !include devices/sonoff_pow_r2.yaml

binary_sensor:

  # This binary sensor tells if the dryer is powered on itself (display)
  - platform: template
    id: powered_on
    name: "${name} On"
    filters:
      - delayed_off: 10s
    lambda: |-
      return id(sensor_cse7766_power).state > 2;

  # This binary sensor tells if the dryer is running or not
  - platform: template
    id: running
    name: "${name} Running"
    filters:
      - delayed_off: 15s
    lambda: |-
      return id(sensor_cse7766_power).state > 75;
