---
# Kitchen Fridge
#
# Our kitchen fridge is hooked up to a Gosund SP1.
# https://frenck.link/gosund-sp1
#
# It just sends out power data to Home Assistant.
#
substitutions:
  label: esp07
  slug: kitchen_fridge
  name: Kitchen Fridge
  description: Monitors our fridge located in the kitchen.
  api_password: !secret esphome_kitchen_fridge_api_password
  ota_password: !secret esphome_kitchen_fridge_ota_password

packages:
  device: !include devices/gosund_sp1.yaml
