---
# Office Playground
#
# This is my ESPHome test setup, using an ESP32.
# Devices in here are not actively used and this file may change
# a lot.
#
substitutions:
  slug: office_playground
  name: Office Playground
  description: Small test device for fiddling
  api_password: !secret esphome_office_playground_api_password
  ota_password: !secret esphome_office_playground_ota_password

packages:
  <<: !include_dir_named common
  board: !include boards/wemos_lolin32.yaml
