---
# Unused; esp04
#
# Currently not in use, but here to be able to set it up
# again easily when needed.
#
# It is added to a regular power bar, so that can be helpful
# at times to get something, temporarly, smart.
#
substitutions:
  label: esp04
  slug: unused_esp04
  name: Unused esp04
  description: Currently not in use.
  api_password: !secret esphome_unused_esp04_api_password
  ota_password: !secret esphome_unused_esp04_ota_password

packages:
  device: !include devices/sonoff_basic.yaml
