---
# This automation turns off our central ventilation
# system, as soon as the bathroom humidity drops
# below 65%.
#
# For us this is a safe value, since turning off
# the ventilation is not possible. Off = low.
#
alias: bathroom_ventilation_low
trigger:
  platform: numeric_state
  entity_id: sensor.bathroom_humidity
  below: 65
action:
  - service: fan.turn_off
    entity_id: fan.attic_ventilation
