---
# Stream server for ESPHome
#
# Custom component for ESPHome to expose a UART stream over WiFi or Ethernet.
# Can be used as a serial-to-wifi bridge as known from ESPLink or ser2net by
# using ESPHome.
#
# This component creates a TCP server listening on port 6638 (by default),
# and relays all data between the connected clients and the serial port.
# It doesn't support any control sequences, telnet options or RFC 2217,
# just raw data.
#
# https://github.com/oxan/esphome-stream-server
#
external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
